id: P001782
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:21:18.295493
source_metadata:
  id: bdr:W29363
  title: གསུང་འབུམ། བློ་བཟང་བསྟན་པ་རྒྱ་མཚོ
  author: ''
  volumes:
    ab49f96edfa64082ac11d0f10b57e9ce:
      image_group_id: I6008
      title: ''
      volume_number: 1
      total_pages: 451
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
